[package]
name = "toy-payments-engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "tpe" # tpe: toy payments engine
path = "src/tpe/lib.rs"

[dependencies]
anyhow = "1.0.63"
serde = "1.0.144"
thiserror = "1.0.33"
